### ISSUE TITLE
IntrospectionQuery is a kind of reserved keyword

### ISSUE THREAD

**Issue by asoorm** [wundergraph/graphql-go-tools#278] opened 2021-08-23 14:20 UTC
Request using Apollo Rover

```
curl --location --request POST 'http://localhost:8080/user/' \
--header 'Content-Type: application/json' \
--data-raw '{"variables":null,"query":"query IntrospectionQuery{\n    _service {\n        sdl\n    }\n}","operationName":"IntrospectionQuery"}'
```

Response:
```
{
    "data": {
        "__schema": {
            "queryType": {
                "name": "Query"
            },
            "mutationType": null,
            "subscriptionType": null,
            "types": [
                {
                    "kind": "SCALAR",
                    "name": "_Any",
                    "description": "",
                    "fields": [],
                    "inputFields": [],
                    "interfaces": [],
...
```

Expected:

```
{
    "data": {
        "_service": {
            "sdl": "extend type Query {\n  me: User\n}\n\ntype User @key(fields: \"id\") {\n  id: ID!\n  name: String\n  username: String\n}\n"
        }
    }
}
```

This is resolved by commenting out  the following check inside `IsIntrospectionQuery`.

```
// pkg/graphql/request.go:117
if r.OperationName == defaultInrospectionQueryName {
    return true, nil
}
```

**Comment by dnerdy** [comment] 2021-11-05 06:04
@jensneuse I see the operation name "IntrospectionQuery" is used in various tests. It's also the name of the introspection query used by the playground. [The spec](https://spec.graphql.org/October2021/#sec-Schema-Introspection) indicates introspection is performed by selecting the `__schema` or `__type` fields on the root query type. The operation name is irrelevant.

Is there any reason to keep the default introspection operation name around?

**Comment by jensneuse** [comment] 2021-11-05 07:16
The problem is that we don't yet have a real resolver for `__schema` and `__type`. That is, we just detect if it's `__schema` and dump back the JSON of the introspection. If we had a real resolver, we could remove this. Are you interested in building one? =) Here's the starting point: https://github.com/jensneuse/graphql-go-tools/tree/master/pkg/introspection

**Comment by dnerdy** [comment] 2021-11-05 21:40
Introspection isn't a priority for us at the moment (though it might become one). Is sniffing for a `__schema` field any different than sniffing the operation name? It seems like we could get rid of operation name sniffing even if schema introspection isn't yet fully implemented.

**Comment by jensneuse** [comment] 2021-11-07 10:18
> Introspection isn't a priority for us at the moment (though it might become one). Is sniffing for a `__schema` field any different than sniffing the operation name? It seems like we could get rid of operation name sniffing even if schema introspection isn't yet fully implemented.

Yes, that's our proposed solution. Although it would be better to have a real resolver.

**Comment by spetrunin** [comment] 2021-12-08 19:30
fixed with https://github.com/TykTechnologies/graphql-go-tools/pull/178

**Closed** 2022-11-18 14:52 UTC
